
services:
  server:
    build: ./server
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb://mongo:27017/asset-tracker
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: